<?php

/**
 * -------------------------------------------------------------------------
 * TreeView plugin for GLPI
 * -------------------------------------------------------------------------
 *
 * LICENSE
 *
 * This file is part of TreeView.
 *
 * TreeView is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * TreeView is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with TreeView. If not, see <http://www.gnu.org/licenses/>.
 * -------------------------------------------------------------------------
 * @copyright Copyright (C) 2007-2023 by Teclib'.
 * @license   GPLv2 https://www.gnu.org/licenses/gpl-2.0.html
 * @link      https://github.com/pluginsGLPI/treeview
 * -------------------------------------------------------------------------
 */

namespace GlpiPlugin\Treeview\Tests;

use DbTestCase;
use PluginTreeviewConfig;

abstract class TreeviewTestCase extends DbTestCase
{
    /**
     * Capture the JavaScript tree markup generated by
     * PluginTreeviewConfig::getNodesFromDb() for the current session
     * (active entity, current user rights).
     *
     * @param int|null $opened_locations_id A top-level location id to expand,
     *                                       so its items get loaded too (the
     *                                       tree only loads items for nodes
     *                                       present in the "nodes" path, same
     *                                       as a client expanding a node).
     */
    protected function getTreeOutput(?int $opened_locations_id = null): string
    {
        $previous_nodes = $_GET['nodes'] ?? null;
        if ($opened_locations_id !== null) {
            $_GET['nodes'] = $opened_locations_id . '.0';
        }

        $config = new PluginTreeviewConfig();
        ob_start();
        $config->getNodesFromDb();
        $output = ob_get_clean();

        if ($previous_nodes === null) {
            unset($_GET['nodes']);
        } else {
            $_GET['nodes'] = $previous_nodes;
        }

        return $output;
    }
}
